/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/building.gltf 
*/
import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
export function Model(props) {
  const { nodes, materials } = useGLTF('models/building.gltf')
  const texture = useTexture("textures/baked.jpg")
  texture.flipY = false
  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texture
  })

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.gharniz.geometry} material={materials.gharniz} scale={0.305} />
      <mesh geometry={nodes['Wood_-_TruStile_-_Doors_-_MDF'].geometry} material={textureMaterial} position={[2.336, 0, 1.166]} scale={0.305} />
      <mesh geometry={nodes.Default_Floor.geometry} material={nodes.Default_Floor.material} scale={0.305} />
      <mesh geometry={nodes['Wood_-_Stained'].geometry} material={materials['windows metal']} position={[-1.458, 0.1, 6.379]} rotation={[0, 0.157, 0]} scale={0.305} />
      <mesh geometry={nodes['Clad_-_White'].geometry} material={nodes['Clad_-_White'].material} position={[-1.458, 0.1, 6.379]} rotation={[0, 0.157, 0]} scale={0.305} />
      <mesh geometry={nodes.Glass.geometry} material={materials['windows glass']} position={[0.797, 0, 5.108]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.305} />
      <mesh geometry={nodes.Aluminum.geometry} material={nodes.Aluminum.material} position={[0.797, 0, 5.108]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.305} />
      <mesh geometry={nodes.Cherry.geometry} material={nodes.Cherry.material} position={[0.797, 0, 5.108]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.305} />
      <mesh geometry={nodes.MineralWool_ALUPROF_Brown.geometry} material={nodes.MineralWool_ALUPROF_Brown.material} position={[-3.365, 0, -7.256]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.305} />
      <mesh geometry={nodes.StainlessSteel_ALUPROF_Grey.geometry} material={materials['Door Handles']} position={[-3.365, 0, -7.256]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.305} />
      <mesh geometry={nodes.Aluminium_ALUPROF_RAL7016_AnthraciteGrey.geometry} material={materials['Entrance Door']} position={[-3.365, 0, -7.256]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.305} />
      <mesh geometry={nodes.Default_Wall.geometry} material={nodes.Default_Wall.material} scale={0.305} />
      <mesh geometry={nodes.Gypsum_Wall_Board.geometry} material={materials['Material.003']} scale={0.305} />
    </group>
  )
}

useGLTF.preload('models/building.gltf')
